import { AIModel } from "../types";

export const AVAILABLE_MODELS: AIModel[] = [
  {
    id: "deepseek-ai/deepseek-r1",
    name: "DeepSeek R1",
    provider: "NVIDIA",
    description: "DeepSeek's flagship open-source reasoning model, powered by reinforcement learning. Famous for detailed step-by-step reasoning processes and exceptional math, logic, and coding mastery.",
    badge: "Advanced Reasoning",
    maxTokens: 4096,
    isVision: false,
  },
  {
    id: "qwen/qwen-2.5-coder-32b-instruct",
    name: "Qwen 2.5 Coder 32B",
    provider: "NVIDIA",
    description: "The state-of-the-art open-source developer model. Unrivaled at writing clean code, bug fixing, algorithmic puzzle solving, and multi-language engineering.",
    badge: "Premier Coding",
    maxTokens: 4096,
    isVision: false,
  },
  {
    id: "microsoft/phi-4",
    name: "Phi-4 (14B)",
    provider: "NVIDIA",
    description: "Microsoft's highly compact and extremely snappy 14B parameter model. Employs next-gen reasoning, math, and logical deduction superior to many huge models.",
    badge: "Ultra Fast + Smart",
    maxTokens: 4096,
    isVision: false,
  },
  {
    id: "qwen/qwen-2.5-72b-instruct",
    name: "Qwen 2.5 72B",
    provider: "NVIDIA",
    description: "Alibaba's advanced 72B general-purpose model. Features stellar multilingual understanding, rich structural responses, high command-following precision, and robust memory.",
    badge: "Advanced Generalist",
    maxTokens: 4096,
    isVision: false,
  },
  {
    id: "meta/llama-3.3-70b-instruct",
    name: "Llama 3.3 70B",
    provider: "NVIDIA",
    description: "Meta's state-of-the-art 70B model hosted on NVIDIA NIM. Exceptional multilingual performance, structured explanations, coding mastery, and swift speeds.",
    badge: "Flagship 3.3",
    maxTokens: 4096,
    isVision: false,
  },
  {
    id: "nvidia/llama-3.1-nemotron-70b-instruct",
    name: "Nemotron 3.1 70B",
    provider: "NVIDIA",
    description: "NVIDIA's custom-tuned Llama model. Excels at highly helpful, beautiful markdown outputs, rich structured explanations, and programming support.",
    badge: "Specially Tuned",
    maxTokens: 4096,
    isVision: false,
  },
  {
    id: "meta/llama-3.1-405b-instruct",
    name: "Llama 3.1 405B",
    provider: "NVIDIA",
    description: "Meta's flagship open LLM hosted by NVIDIA NIM. Massive reasoning, perfect for deep research, coding, logic trees, or complex summarization.",
    badge: "Massive Reasoning",
    maxTokens: 4096,
    isVision: false,
  },
  {
    id: "mistralai/mixtral-8x22b-instruct-v0.1",
    name: "Mixtral 8x22B",
    provider: "NVIDIA",
    description: "Powerful Mixture of Experts (MoE) engineered by Mistral AI. Optimized for heavy logical parsing, formatting, and high density analytics.",
    badge: "Logical Specialist",
    maxTokens: 4096,
    isVision: false,
  },
];
